export const englishLandingPages = {
  "planning-law": {
    metadata: {
      title: "French planning law: permits and appeals",
      description: "Sophie Maréchal advises on planning projects in Paris, including building permits, prior declarations, planning authorisations and administrative appeals.",
      path: "/en/planning-law",
      keywords: ["French planning law", "building permit France", "planning appeal Paris"],
    },
    serviceType: "French planning law",
    breadcrumbs: [{ label: "Home", href: "/en" }, { label: "Practice areas", href: "/en/practice-areas" }, { label: "Planning law" }],
    eyebrow: "French planning law",
    title: "Building, developing land or challenging a decision: putting your planning project on a sound legal footing",
    intro: "Advice before an application for planning authorisation is made and after an adverse decision, with a clear assessment of the risks and available remedies.",
    sections: [
      {
        eyebrow: "Overview",
        title: "Putting the project on a sound legal footing, before and after the decision",
        paragraphs: [
          "Sophie Maréchal, a lawyer practising in French planning law, assists individuals, businesses and local authorities with planning-authorisation applications and disputes with public authorities.",
          "Planning law comprises the rules governing building and land development: what may be built, to what height, how far from a property boundary and subject to which restrictions.",
          "The procedures can be complex, and decisions by the relevant authority—whether a town hall or prefecture—can have significant implications for your project.",
          "Her role is to help put your project on a sound legal footing and protect your interests by providing clear, accessible advice at every stage, from preparing the application through to any administrative challenge or court proceedings.",
        ],
      },
      {
        eyebrow: "Authorisations",
        title: "Planning authorisations",
        paragraphs: [
          "Sophie Maréchal assists with applications for planning authorisation. Her work includes assessing the project’s legal feasibility, identifying the applicable rules and assisting with the preparation of the application.",
        ],
        points: ["A building permit (permis de construire)", "A development permit (permis d’aménager)", "A prior declaration of works (déclaration préalable de travaux)"],
      },
      {
        eyebrow: "Challenges",
        title: "Challenging decisions",
        paragraphs: [
          "Where an adverse decision is made, it can often be challenged by an administrative request for reconsideration (recours gracieux)—a request asking the authority to review its decision—or by bringing proceedings before the French Administrative Court.",
          "She advises on the available remedies and represents clients before the French Administrative Court to protect their projects and rights.",
        ],
        points: ["A refusal of a building permit", "A refusal of a development permit", "A decision objecting to a prior declaration", "Any decision imposing unlawful requirements"],
      },
      {
        eyebrow: "Approach",
        title: "Protecting planning projects and managing legal risk",
        paragraphs: [
          "She provides tailored assistance whether you are pursuing a project—construction, an extension, subdivision of land or a change of use—or facing an adverse administrative decision concerning a planning authorisation.",
          "If court proceedings are unnecessary or unsuitable, she will explain this openly and may suggest a fresh application, changes to the project or an administrative request for reconsideration.",
        ],
      },
    ],
    proofTitle: "Advice before and after the administrative decision",
    proofItems: [
      { title: "Early-stage advice", text: "Check the applicable planning rules and identify the legal risks before filing." },
      { title: "Application review", text: "Strengthen the documents and legal presentation of the proposed project." },
      { title: "Decision analysis", text: "Review the reasons for a refusal or another adverse planning decision." },
      { title: "Appeal strategy", text: "Compare reconsideration, regularisation, a new application and court proceedings." },
    ],
    faqTitle: "Planning law FAQs",
    faqItems: [
      { question: "When should I consult a planning lawyer?", answer: "A planning lawyer can assist before an application for planning authorisation is submitted, to put your project on a sound legal footing, check the applicable rules and assess the risk of refusal, or after an adverse decision, to consider the available remedies." },
      { question: "Can a refusal of a building permit be challenged?", answer: "Yes. Depending on the circumstances, a refusal may be challenged by an administrative request for reconsideration or by bringing proceedings before the French Administrative Court." },
      { question: "Can a lawyer help prepare a building permit application?", answer: "Yes. Legal assistance can help check the rules applying to the land, including the local development plan, easements and public-law restrictions, anticipate obstacles and prepare a legally more robust application." },
    ],
    relatedTitle: "Related planning law guidance",
    relatedItems: [
      { href: "/en/planning-law-lawyer-paris", label: "Planning law lawyer in Paris", text: "Advice and representation for planning projects in Paris." },
      { href: "/en/building-permit-refusal-lawyer-paris", label: "Building permit refusal", text: "Review the reasons for refusal and available remedies." },
      { href: "/en/contact", label: "Discuss your project", text: "Send the decision, plans and relevant correspondence." },
    ],
    ctaTitle: "Discuss a planning project or decision",
    ctaText: "An initial consultation helps identify the applicable rules, relevant documents, deadlines and realistic strategic options.",
  },

  "immigration-law": {
    metadata: {
      title: "French immigration law: OQTF appeals",
      description: "Sophie Maréchal assists in Paris with residence permits, naturalisation, nationality matters and challenges to orders to leave French territory (OQTF).",
      path: "/en/immigration-law",
      keywords: ["French immigration law", "residence permit France", "OQTF appeal Paris"],
    },
    serviceType: "French immigration law",
    breadcrumbs: [{ label: "Home", href: "/en" }, { label: "Practice areas", href: "/en/practice-areas" }, { label: "Immigration law" }],
    eyebrow: "French immigration and nationality law",
    title: "Residence permit applications, naturalisation and orders to leave French territory (OQTF): clear guidance at every stage",
    intro: "A strategic approach to put your applications on a sound legal footing, protect your rights and anticipate difficulties when dealing with the French authorities.",
    sections: [
      {
        eyebrow: "Overview",
        title: "A human, technical and high-stakes area of law",
        paragraphs: [
          "French immigration law comprises the rules governing foreign nationals’ residence, employment and settlement in France.",
          "These procedures can be complex, lengthy and stressful. An immigration lawyer’s role is to guide you at every stage, help ensure that your application is legally robust and protect your rights.",
          "You may wish to consult a lawyer if you plan to apply for a residence permit or French nationality, or challenge an adverse decision such as a refusal, an OQTF or certain asylum decisions.",
        ],
      },
      {
        eyebrow: "Applications",
        title: "Residence permits and French nationality applications",
        paragraphs: [
          "Sophie Maréchal helps clients prepare and submit residence permit applications, taking account of their personal and professional circumstances.",
          "She also assists with applications to acquire French nationality, whether by decree or declaration, helping to prepare a complete application and anticipate potential difficulties.",
        ],
        points: ["‘Employee’ residence permits and residence permits for shortage occupations", "‘Private and family life’ residence permits", "‘Talent’ residence permits", "‘Student’ residence permits"],
      },
      {
        eyebrow: "Challenges",
        title: "Challenges and proceedings",
        paragraphs: [
          "When an authority refuses an application, it is often possible to challenge the decision. She advises and represents clients following refusals of residence permits, refusals of family reunification and OQTFs, with or without a period for voluntary departure.",
          "She also appears before the French National Court of Asylum (Cour nationale du droit d’asile – CNDA) in appeals against certain decisions refusing international protection.",
        ],
      },
      {
        eyebrow: "Approach",
        title: "The lawyer’s advisory role",
        paragraphs: [
          "The lawyer’s role is to advise you in your best interests. Sophie Maréchal carries out a detailed, tailored legal assessment of your circumstances during a consultation.",
          "If she considers that you do not meet the requirements for a residence permit or naturalisation, she will tell you so openly.",
        ],
      },
    ],
    proofTitle: "A tailored assessment of the procedure and evidence",
    proofItems: [
      { title: "Applications", text: "Identify the relevant legal basis and organise a clear set of documents." },
      { title: "Adverse decisions", text: "Read the reasons, notification and available remedies without delay." },
      { title: "Personal circumstances", text: "Connect the legal analysis with family life, work, studies and residence in France." },
      { title: "Proceedings", text: "Prepare administrative or court proceedings where they are appropriate." },
    ],
    faqTitle: "Immigration law FAQs",
    faqItems: [
      { question: "When should I consult an immigration lawyer?", answer: "It is helpful to consult an immigration lawyer when preparing a residence permit or naturalisation application, or when challenging a refusal, an order to leave French territory (OQTF) or a refusal of family reunification." },
      { question: "Can a refusal of a residence permit be challenged?", answer: "Yes. Depending on the circumstances, it may be challenged by an administrative request for reconsideration or by proceedings before the French Administrative Court, after the applicable time limits have been reviewed." },
      { question: "Can a lawyer assist with a naturalisation application?", answer: "Yes. Legal assistance can help prepare a more robust application, anticipate potential difficulties and put the naturalisation process on a sound legal footing." },
    ],
    relatedTitle: "Related immigration and nationality pages",
    relatedItems: [
      { href: "/en/immigration-lawyer-paris", label: "Immigration lawyer in Paris", text: "Residence applications and challenges to decisions by the prefecture." },
      { href: "/en/oqtf-lawyer-paris", label: "OQTF lawyer in Paris", text: "Check urgent deadlines and the evidence needed for an appeal." },
      { href: "/en/talent-passport-resident-card-lawyer-paris", label: "Talent residence permit and resident card", text: "Compare permits and prepare an application or renewal." },
      { href: "/en/french-nationality-law", label: "French nationality law", text: "Naturalisation applications, assessment and adverse decisions." },
    ],
    ctaTitle: "Discuss an application or administrative decision",
    ctaText: "Send the complete decision and proof of notification if a deadline may be running. For an application, explain your circumstances and the permit sought.",
  },

  "french-nationality-law": {
    metadata: {
      title: "French nationality law: naturalisation",
      description: "Understand French naturalisation: the procedure, eligibility criteria, civic examination, decisions and appeals, with a lawyer in Paris.",
      path: "/en/french-nationality-law",
      keywords: ["French nationality law", "French naturalisation", "naturalisation application", "naturalisation appeal"],
    },
    serviceType: "French nationality law",
    breadcrumbs: [{ label: "Home", href: "/en" }, { label: "Practice areas", href: "/en/practice-areas" }, { label: "French nationality law" }],
    eyebrow: "French nationality law",
    title: "French nationality law: naturalisation",
    intro: "Understanding the correct legal route, the factors considered, the stages of the application and the remedies available following an adverse decision.",
    notice: "This page focuses primarily on naturalisation by decree. Declarations of nationality and other routes to acquisition are governed by different rules, which must be assessed in light of the applicant’s individual circumstances.",
    sections: [
      { eyebrow: "Choosing the correct route", title: "Identifying the appropriate route to French nationality", paragraphs: ["Naturalisation by decree is one route to acquiring French nationality. It is distinct from declarations of nationality based on marriage or certain family relationships, and from the rules governing acquisition by birth or parentage.", "The first step is therefore to analyse the applicant’s position and identify the correct legal basis. Starting an application under an unsuitable route can cause delay and lead to the collection of documents that do not address the applicable requirements."] },
      { eyebrow: "Naturalisation", title: "A decision made following an assessment of the applicant’s circumstances as a whole", paragraphs: ["Naturalisation by decree is granted following an application by a foreign national. Meeting the requirements makes an applicant eligible to apply but does not guarantee approval: the French authorities retain discretion when determining the application.", "The authorities consider, in particular, residence and the applicant’s centre of interests in France, lawful immigration status, assimilation into French society, proficiency in French, professional integration, financial resources, family circumstances, and matters relating to good character and public order."] },
      { eyebrow: "2026 requirements", title: "French-language proficiency, civic examination and interview", paragraphs: ["Since 1 January 2026, an application for naturalisation by decree generally requires evidence of B2-level French, both spoken and written, and a pass in the civic examination. Adjustments and exemptions are available in circumstances prescribed by law.", "The civic examination does not replace the interview with the French authorities. The application must remain consistent with the information provided during the assessment process and with any changes in circumstances reported after submission."] },
      { eyebrow: "Application", title: "Preparing a clear and internally consistent set of supporting documents", paragraphs: ["Documents relating to civil status, address, immigration status, family circumstances, financial resources and tax must present a coherent picture. Depending on their nature and country of origin, foreign documents may require a translation, legalisation or an apostille.", "An initial review can identify discrepancies between dates, periods for which evidence is insufficient, changes in employment or family circumstances, and documents requiring further explanation."], points: ["Check the applicable procedure and competent authority", "Check the consistency of civil-status documents and translations", "Document residence, employment, financial resources and family life", "Prepare for the civic examination, interview and requests for further documents"] },
      { eyebrow: "Decision", title: "Understanding inadmissibility, rejection, deferral or closure without further action", paragraphs: ["The precise nature of the decision determines the available response. A finding of inadmissibility, a rejection, a deferral and closure without further action are based on different grounds and do not necessarily carry the same route of challenge.", "To challenge certain decisions by the prefect in the naturalisation-by-decree procedure, a mandatory prior administrative appeal must be made to the Ministry of the Interior before court proceedings. The date of notification and the available remedies must be checked immediately."] },
    ],
    proofTitle: "How legal advice can help put your application on a sound footing",
    proofItems: [
      { title: "Choosing the correct route", text: "Identify the correct route to French nationality and the competent authority before starting." },
      { title: "Consistency of supporting documents", text: "Identify missing documents, inconsistencies and matters requiring an explanation." },
      { title: "Monitoring the application", text: "Prepare responses to requests for further documents and report changes in circumstances." },
      { title: "Reviewing the decision", text: "Identify the precise nature of an adverse decision and the available route of challenge." },
    ],
    faqTitle: "Frequently asked questions about French naturalisation",
    faqItems: [
      { question: "Are five years’ residence enough to be naturalised?", answer: "No. Five years’ habitual residence is the general rule, subject to exceptions, but the French authorities assess the applicant’s circumstances as a whole. Eligibility does not create an automatic entitlement to a favourable decision." },
      { question: "What level of French is required for naturalisation in 2026?", answer: "Since 1 January 2026, applicants are generally required to demonstrate B2-level French, both spoken and written. The accepted evidence and any adjustments or exemptions are prescribed by law." },
      { question: "Does the civic examination replace the interview at the prefecture?", answer: "No. Passing the civic examination and attending the interview conducted by the French authorities are separate stages." },
      { question: "Must a naturalisation application always be made online?", answer: "Online submission is standard for many applicants living in France, but different arrangements apply depending on residence and individual circumstances." },
      { question: "How can an adverse naturalisation decision be challenged?", answer: "For certain decisions, a mandatory prior administrative appeal must be made to the Ministry of the Interior before court proceedings. The complete decision and notice should be reviewed without delay." },
    ],
    updatedAt: "1 September 2026",
    sourceItems: [
      { label: "Service-Public.fr (in French) — French naturalisation by decree", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F2213" },
      { label: "Service-Public.fr (in French) — How can French nationality be acquired?", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/N111" },
      { label: "Service-Public.fr (in French) — Evidence of French-language proficiency", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F11926" },
      { label: "Ministry of the Interior (in French) — Challenges relating to access to French nationality", href: "https://www.immigration.interieur.gouv.fr/devenir-francais/contentieux-de-lacces-a-nationalite-francaise" },
    ],
    relatedTitle: "Next steps for your circumstances",
    relatedItems: [
      { href: "/en/naturalisation-lawyer-paris", label: "French naturalisation lawyer in Paris", text: "Legal assistance before submission, during assessment or after an adverse decision." },
      { href: "/en/immigration-law", label: "French immigration law", text: "Residence permits, decisions by the prefecture and OQTFs." },
      { href: "/en/immigration-lawyer-paris", label: "Immigration lawyer in Paris", text: "Tailored advice on administrative applications and challenges." },
      { href: "/en/contact", label: "Contact the firm", text: "Tell us about your application, assessment issue or decision." },
    ],
    ctaTitle: "Have a naturalisation application or decision reviewed",
    ctaText: "The initial consultation helps identify the applicable procedure, potential weaknesses and any time limits stated in the decision notice. No outcome or processing time can be guaranteed.",
  },

  "public-law-lawyer-paris": {
    metadata: { title: "Public law lawyer in Paris", description: "Sophie Maréchal, also searched for as Sophie Marechal, advises and represents individuals and professionals in public law matters in Paris.", path: "/en/public-law-lawyer-paris", keywords: ["public law lawyer Paris", "administrative law lawyer Paris", "Sophie Marechal lawyer"] },
    serviceType: "French public and administrative law",
    breadcrumbs: [{ label: "Home", href: "/en" }, { label: "Public law lawyer in Paris" }],
    eyebrow: "Public law · Paris", title: "Public law lawyer in Paris", intro: "Sophie Maréchal’s law firm handles public law matters in Paris, including planning law, immigration law, nationality law and administrative appeals.",
    sections: [
      { eyebrow: "Administrative decision", title: "When an administrative decision calls for a legal response", paragraphs: ["Public law covers the rules governing dealings with public authorities, administrative decisions and proceedings before the administrative courts. It applies to refusals, penalties, authorisations, stalled applications and decisions that are difficult to understand.", "Sophie Maréchal advises and represents individuals and professionals, providing a structured legal analysis and a clear explanation of the available options."] },
      { eyebrow: "Areas of practice", title: "Planning, immigration and nationality law: three areas of public law", paragraphs: ["The firm’s main practice areas are planning law, immigration law and nationality law. These fields often involve an administrative decision that must be analysed, secured or challenged within strict time limits."], points: ["Analysis of individual administrative decisions", "Administrative appeals and court proceedings", "Litigation before the administrative courts", "Strategic advice before an application or procedure"] },
      { eyebrow: "Case assessment", title: "Clarifying deadlines, documents and the appropriate route of appeal", paragraphs: ["The first step is to understand the client’s situation, objectives and deadlines. In public law, an effective course of action often depends on the chronology and the documents already filed.", "If a particular course of action is unsuitable, or if an administrative step must be taken first, this should be identified before unnecessary proceedings are commenced."] },
      { eyebrow: "The firm", title: "A Paris law firm for administrative matters", paragraphs: ["Consultations are available by appointment at 11 boulevard de Sébastopol, 75001 Paris, while remote support is also available where appropriate.", "Sophie Maréchal is also searched for as Sophie Marechal, without the accent. Both spellings refer to the same public law firm in Paris."] },
    ],
    proofTitle: "Relevant experience and qualifications",
    proofItems: [
      { title: "Public law", text: "Master’s degrees in Public Affairs from Sciences Po Paris and General Public Law from Paris 1 Panthéon-Sorbonne." },
      { title: "Public administration", text: "Seven years as a hospital director provide insight into administrative and institutional processes." },
      { title: "Paris Bar", text: "EFB training in public law and immigration law before taking the oath in 2024." },
      { title: "Approach", text: "Clear explanations of deadlines, risks, remedies and supporting documents." },
    ],
    faqTitle: "Public law in Paris: frequently asked questions",
    faqItems: [
      { question: "When should I consult a public law lawyer in Paris?", answer: "When an administrative decision affects personal, professional or property interests, for example a refusal, authorisation, OQTF or proceedings before the administrative court." },
      { question: "Does public law only concern public authorities?", answer: "No. It also concerns individuals, associations, businesses and project owners faced with an administrative decision or procedure." },
      { question: "Does the firm handle cases before the Paris Administrative Court?", answer: "The firm advises and represents clients in administrative matters and disputes in Paris, including before the administrative courts when required." },
      { question: "Do Sophie Maréchal and Sophie Marechal refer to the same lawyer?", answer: "Yes. Both spellings refer to Sophie Maréchal, a member of the Paris Bar." },
    ],
    relatedTitle: "Explore the firm’s public law practice areas",
    relatedItems: [
      { href: "/en/planning-law-lawyer-paris", label: "Planning law lawyer in Paris", text: "Planning permissions, building permits and appeals." },
      { href: "/en/immigration-lawyer-paris", label: "Immigration lawyer in Paris", text: "Residence permits, naturalisation, OQTFs and refusals by the prefecture." },
      { href: "/en/french-nationality-law", label: "French nationality law", text: "French naturalisation applications, assessment and adverse decisions." },
      { href: "/en/oqtf-lawyer-paris", label: "OQTF lawyer in Paris", text: "Deadlines, decisions by the prefecture and litigation strategy." },
    ],
  },

  "planning-law-lawyer-paris": {
    metadata: { title: "Planning law lawyer in Paris", description: "Planning law lawyer in Paris, Sophie Maréchal assists with building permits, prior declarations, planning permissions and appeals.", path: "/en/planning-law-lawyer-paris", keywords: ["planning law lawyer Paris", "urban planning lawyer Paris", "building permit lawyer Paris"] },
    serviceType: "French planning law",
    breadcrumbs: [{ label: "Home", href: "/en" }, { label: "Planning law lawyer in Paris" }],
    eyebrow: "Planning law · Paris", title: "Planning law lawyer in Paris", intro: "Advice before planning permission is sought and assistance following adverse decisions, with a clear assessment of the risks and available remedies.",
    sections: [
      { eyebrow: "Project", title: "Check the legal framework before building or developing land", paragraphs: ["Planning law comprises the rules governing construction and land development: what may be built, to what height, at what distance from a property boundary and subject to which restrictions.", "Sophie Maréchal assists individuals, professionals and local authorities with planning permission procedures and disputes with the authorities."] },
      { eyebrow: "Permissions", title: "Building permits, prior declarations and conditions: understanding the decision", paragraphs: ["The firm advises before a planning permission application is filed, helping to prepare the application and secure the project.", "It also assists after an adverse decision, providing a clear assessment of the risks and available remedies."], points: ["Building permits and prior declarations", "Advice, preparation of the application and project risk management", "Administrative request for reconsideration", "Court proceedings before the administrative court"] },
      { eyebrow: "After a refusal", title: "Choosing between an appeal, regularisation or a new application", paragraphs: ["A building permit refusal, an objection to a prior declaration or a disputed condition must be read carefully. Some projects can be regularised or defended.", "The strategy may involve discussions with the authorities, reconsideration, a new application, changes to the project or court proceedings."] },
      { eyebrow: "The firm", title: "Planning law advice and representation in Paris", paragraphs: ["The firm is located at 11 boulevard de Sébastopol in Paris and assists with planning matters in Paris and the wider Île-de-France region.", "The main planning law page and dedicated building permit refusal page provide further information."] },
    ],
    proofItems: [
      { title: "Public law", text: "A practice grounded in public law and administrative appeals." },
      { title: "Before and after a decision", text: "Assistance before filing or after an adverse decision." },
      { title: "Case-specific risks", text: "Assessment of the rules, documents, correspondence and deadlines." },
      { title: "Paris", text: "Consultations in Paris’s 1st arrondissement or remotely." },
    ],
    faqTitle: "Planning law in Paris: frequently asked questions",
    faqItems: [
      { question: "When should I consult a planning law lawyer in Paris?", answer: "Before a permission application to secure the project and assess the risk of refusal, or after an adverse decision to consider the remedies." },
      { question: "Can a building permit refusal be challenged?", answer: "Yes. Depending on the case, it may be challenged by reconsideration or proceedings before the administrative court." },
      { question: "Does the firm assist both individuals and professionals?", answer: "Yes. The firm assists individuals, professionals, project owners and local authorities." },
      { question: "Why have a case reviewed before filing?", answer: "An early review identifies applicable rules, refusal risks and documents that should be strengthened." },
    ],
    relatedTitle: "Related planning law pages",
    relatedItems: [
      { href: "/en/planning-law", label: "Planning law", text: "An overview of planning permissions and appeals." },
      { href: "/en/building-permit-refusal-lawyer-paris", label: "Building permit refusal in Paris", text: "Assess the reasons and available remedies." },
      { href: "/en/public-law-lawyer-paris", label: "Public law lawyer in Paris", text: "The firm’s approach to administrative law." },
      { href: "/en/contact", label: "Contact the firm", text: "Tell us about a project or planning decision." },
    ],
  },

  "immigration-lawyer-paris": {
    metadata: { title: "Immigration lawyer in Paris", description: "Sophie Maréchal assists in Paris with residence permit applications, talent residence permits and resident cards, residence permit refusals, OQTFs and appeals.", path: "/en/immigration-lawyer-paris", keywords: ["immigration lawyer Paris", "residence permit lawyer Paris", "OQTF appeal lawyer Paris"] },
    serviceType: "French immigration law",
    breadcrumbs: [{ label: "Home", href: "/en" }, { label: "Practice areas", href: "/en/practice-areas" }, { label: "Immigration law", href: "/en/immigration-law" }, { label: "Immigration lawyer in Paris" }],
    eyebrow: "Immigration law · Paris", title: "Immigration lawyer in Paris", intro: "The firm assists with residence permit applications and refusals, OQTFs and immigration appeals in Paris.",
    sections: [
      { eyebrow: "Applications", title: "Prepare a clear, complete and consistent residence permit application", paragraphs: ["French immigration law involves first-time residence permit applications, changes of status, renewals, talent residence permits, resident cards and family reunification.", "The quality and consistency of the supporting documents are often decisive. The firm assists in light of the applicant’s personal, family, professional or academic circumstances."] },
      { eyebrow: "Decision by the prefecture", title: "Appeal a refusal, an OQTF or another adverse measure", paragraphs: ["When an adverse decision is received, the time allowed to act may be very short. It is essential to identify the precise decision, check the notification date, read the reasons and gather the relevant evidence quickly.", "Sophie Maréchal represents clients in appeals against express or implied refusals of residence permits, OQTFs and refusals of family reunification. She also assists following certain asylum refusals."], points: ["Analyse the reasons for the decision", "Gather personal, family and professional evidence", "Check whether the authorities followed the correct procedure", "Prepare proceedings before the administrative court or National Court of Asylum"] },
      { eyebrow: "Personal circumstances", title: "Connect the procedure with family life, work and residence in France", paragraphs: ["Immigration matters affect family life, work, studies and settling in France. The firm identifies the real issues before recommending a strategy.", "If the requirements are not met, or a proposed course is unsuitable, the firm explains this clearly to avoid an unnecessary or unviable application."] },
      { eyebrow: "The firm", title: "An initial consultation to identify deadlines and supporting documents", paragraphs: ["Consultations are available by appointment in Paris, and some matters can be handled remotely.", "For people who have received an OQTF, a dedicated page explains the appeal process and why the situation must be assessed quickly."] },
    ],
    proofItems: [
      { title: "Immigration law", text: "EFB training in public law and immigration law before taking the oath." },
      { title: "Administrative decisions", text: "A public-law background supports methodical analysis of decisions by the prefecture." },
      { title: "Deadlines", text: "Prompt checks of the applicable time limits and supporting documents." },
      { title: "Individual circumstances", text: "Each case is assessed in light of residence, family, work, studies, health and integration." },
    ],
    faqTitle: "Immigration law in Paris: frequently asked questions",
    faqItems: [
      { question: "When should I consult an immigration lawyer in Paris?", answer: "Before applying for or renewing a residence permit, if difficulties arise during processing, or after receiving a refusal or OQTF." },
      { question: "Does the firm represent people who have received an OQTF?", answer: "Yes. The firm represents people who have received an OQTF, whether or not it includes a period for voluntary departure." },
      { question: "Can a refusal to issue or renew a residence permit be challenged?", answer: "Yes, provided that the relevant deadline has not expired and the available remedy is appropriate." },
      { question: "Can the lawyer help before a residence permit application is filed?", answer: "Yes. She can assess the circumstances, identify possible permits and organise the evidence before filing." },
    ],
    relatedTitle: "Related immigration law pages",
    relatedItems: [
      { href: "/en/immigration-law", label: "Immigration law", text: "An overview of applications and appeals." },
      { href: "/en/oqtf-lawyer-paris", label: "OQTF lawyer in Paris", text: "Challenge an order to leave French territory." },
      { href: "/en/talent-passport-resident-card-lawyer-paris", label: "Talent residence permit and resident card", text: "Compare permits and plan for renewal." },
      { href: "/en/french-nationality-law", label: "French nationality law", text: "Separate information on naturalisation." },
    ],
  },

  "oqtf-lawyer-paris": {
    metadata: { title: "OQTF lawyer in Paris", description: "Sophie Maréchal assists people who have received an OQTF in Paris by reviewing the decision, identifying appeal deadlines and developing a litigation strategy.", path: "/en/oqtf-lawyer-paris", keywords: ["OQTF lawyer Paris", "OQTF appeal Paris", "order to leave France lawyer Paris"] },
    serviceType: "Appeals against orders to leave French territory (OQTF)",
    breadcrumbs: [{ label: "Home", href: "/en" }, { label: "Immigration law", href: "/en/immigration-law" }, { label: "OQTF lawyer in Paris" }],
    eyebrow: "Immigration law · Paris", title: "OQTF lawyer in Paris", intro: "The firm assists people who have received an OQTF in identifying the deadlines, available remedies and supporting documents that must be gathered quickly.",
    notice: "The appeal deadline depends on the decision and the person’s circumstances. The complete document and proof of notification must be reviewed immediately.",
    sections: [
      { eyebrow: "Definition", title: "What an order to leave French territory means", paragraphs: ["An OQTF is an administrative decision issued by the prefect ordering a foreign national to leave France. It usually provides a period for voluntary departure, generally 30 days, but may also require departure without delay.", "Receiving an OQTF does not necessarily mean that removal is inevitable. You have the right to challenge the decision before a court."] },
      { eyebrow: "Deadlines", title: "Appeal deadlines you must not miss", paragraphs: ["The deadline starts on notification—that is, on the day you receive or sign the document—not when you read or become aware of it later."], points: ["30 days for an OQTF allowing voluntary departure", "7 days for an OQTF accompanied by an assignation à résidence (residence restriction)", "48 hours for an OQTF where the person has been placed in an administrative detention centre", "Consult a lawyer promptly to avoid procedural errors"] },
      { eyebrow: "Documents", title: "The first steps to take after receiving an OQTF", paragraphs: ["Read the document carefully and identify the notification date, the stated deadline and appeal routes.", "Gather evidence of residence, work and family life, identity documents, and proof of your presence and length of residence in France.", "Do not leave France before consulting a lawyer, unless you have decided to depart voluntarily."] },
    ],
    proofTitle: "A rapid, document-based assessment",
    proofItems: [
      { title: "Complete decision", text: "Review every page, the reasons and any accompanying measures." },
      { title: "Notification", text: "Establish the date and method of notification before calculating a deadline." },
      { title: "Evidence", text: "Organise the relevant evidence of residence, family, work and personal circumstances." },
      { title: "Proceedings", text: "Prepare the appropriate appeal and urgent applications where legally relevant." },
    ],
    faqTitle: "OQTFs in Paris: frequently asked questions",
    faqItems: [
      { question: "What is an OQTF?", answer: "An OQTF is a decision issued by the prefect ordering a foreign national to leave France. It may allow voluntary departure or require departure without delay." },
      { question: "What are the deadlines for appealing an OQTF?", answer: "The deadline depends on the circumstances: 30 days in the general case, 7 days where the person is subject to an assignation à résidence, and 48 hours in administrative detention." },
      { question: "What should I do as soon as I receive an OQTF?", answer: "Read the complete decision, check notification, identify the deadline, seek advice promptly and gather the relevant supporting documents." },
    ],
    relatedItems: [
      { href: "/en/immigration-law", label: "French immigration law", text: "Residence permits and challenges to decisions by the prefecture." },
      { href: "/en/immigration-lawyer-paris", label: "Immigration lawyer in Paris", text: "Legal assistance with applications and appeals." },
      { href: "/en/contact", label: "Send the decision", text: "Provide the complete document and proof of notification." },
    ],
    ctaTitle: "Have the OQTF and notification reviewed promptly",
    ctaText: "Send every page of the decision, the envelope or notification record, and the main documents describing your situation in France.",
  },

  "building-permit-refusal-lawyer-paris": {
    metadata: { title: "Building permit refusal lawyer in Paris", description: "Sophie Maréchal assists with appeals against building permit refusals in Paris, including case analysis, strategy and administrative court proceedings.", path: "/en/building-permit-refusal-lawyer-paris", keywords: ["building permit refusal lawyer Paris", "building permit lawyer Paris", "appeal building permit refusal Paris"] },
    serviceType: "Challenges to refusals of building permits",
    breadcrumbs: [{ label: "Home", href: "/en" }, { label: "Planning law", href: "/en/planning-law" }, { label: "Building permit refusal lawyer in Paris" }],
    eyebrow: "Planning law · Paris", title: "Building permit refusal lawyer in Paris", intro: "The firm advises on and challenges building permit refusals in Paris, providing a clear assessment of the reasons and available remedies.",
    sections: [
      { eyebrow: "Refusal", title: "Understand the reasons before changing or challenging the project", paragraphs: ["A building permit refusal does not necessarily mean that the project is legally impossible. The first step is to understand the precise reasons given by the authorities.", "A technical review of the application and applicable planning rules can identify possible grounds of appeal or adjustments to the project."] },
      { eyebrow: "Assessment", title: "Local development plan (PLU), documents and reasons: key points to review", paragraphs: ["The firm examines whether the refusal is consistent, the documents filed, the planning rules applying to the land and whether reconsideration or court proceedings may be appropriate."], points: ["Legal reasons for the refusal", "Rules in the local development plan (PLU) and applicable easements", "Possibility of regularising the project", "Administrative appeal or litigation strategy"] },
      { eyebrow: "Next steps for the project", title: "Request for reconsideration, court proceedings or a new application", paragraphs: ["The aim is to secure the best strategy: seek withdrawal of the decision, prepare a new application or bring proceedings before the administrative court.", "The firm assists individuals and professionals in Paris in challenging building permit refusals and other adverse planning decisions."] },
    ],
    proofItems: [
      { title: "Reasons", text: "Compare each reason for refusal with the applicable planning rules." },
      { title: "Application", text: "Review the plans, forms, supporting documents and correspondence." },
      { title: "Options", text: "Assess regularisation, a revised application, reconsideration or proceedings." },
      { title: "Deadlines", text: "Check the notification and preserve the relevant appeal deadline." },
    ],
    faqTitle: "Building permit refusals: frequently asked questions",
    faqItems: [
      { question: "Can a building permit refusal be challenged?", answer: "Yes. Depending on the circumstances and deadlines, it may be challenged through reconsideration or proceedings before the administrative court." },
      { question: "What does a lawyer review after a building permit refusal?", answer: "The reasons, the planning rules relied on, the prospects of an appeal and the evidence needed to defend the project." },
      { question: "Do I need to act quickly after a refusal?", answer: "Yes. Planning appeal deadlines are strictly regulated. A prompt assessment helps preserve the opportunity to challenge the decision." },
    ],
    relatedItems: [
      { href: "/en/planning-law", label: "Planning law", text: "Planning permissions, project advice and appeals." },
      { href: "/en/planning-law-lawyer-paris", label: "Planning law lawyer in Paris", text: "Advice before and after a planning decision." },
      { href: "/en/contact", label: "Discuss the refusal", text: "Send the complete decision and planning documents." },
    ],
  },

  "talent-passport-resident-card-lawyer-paris": {
    metadata: { title: "Talent and resident card lawyer in Paris", description: "Sophie Maréchal assists in Paris with talent residence permit and resident card applications, renewals, refusals and appeals.", path: "/en/talent-passport-resident-card-lawyer-paris", keywords: ["talent passport lawyer Paris", "talent residence permit lawyer Paris", "resident card lawyer Paris"] },
    serviceType: "Talent residence permits and resident cards",
    breadcrumbs: [{ label: "Home", href: "/en" }, { label: "Practice areas", href: "/en/practice-areas" }, { label: "Immigration law", href: "/en/immigration-law" }, { label: "Talent residence permit and resident card" }],
    eyebrow: "Immigration law · Paris", title: "Talent residence permit and resident card lawyer in Paris", intro: "The firm helps you identify the appropriate permit, prepare a consistent application, plan ahead for renewal and assess an adverse decision.",
    notice: "Requirements vary according to the legal basis, nationality, place of residence and permit already held. Thresholds, documents and filing procedures must be checked as at the date of the application.",
    sections: [
      { eyebrow: "Guidance", title: "Distinguish between two permits governed by different rules", paragraphs: ["The multi-year ‘talent’ residence permit covers professional, scientific, artistic and economic circumstances. Each category has its own requirements and documents.", "It is still called a ‘Talent Passport’ in some visas, forms and contexts. The exact wording and requirements must be checked.", "A resident card is not simply a longer version of the talent residence permit. It is available on several legal grounds, with special regimes for certain nationalities."] },
      { eyebrow: "Talent residence permit", title: "Match the correct legal ground to the professional or economic project", paragraphs: ["The application must correspond exactly to the category relied on: highly qualified employment, research, setting up a business, an economic project, artistic work or another situation provided for by law.", "The procedure differs depending on whether the person is in France or abroad. Thresholds and documents may change and should be checked at filing."], points: ["Highly qualified employee", "EU Blue Card", "Researcher", "Business founder or project owner", "Company director", "Artistic and cultural profession", "National or international reputation", "Medical or pharmaceutical profession"] },
      { eyebrow: "Resident card", title: "Identify the exact legal basis before assessing the requirements", paragraphs: ["A ten-year resident card may be requested in several situations, including ties in France, protected statuses or other grounds under immigration law. The EU long-term resident card generally requires five years of lawful and uninterrupted residence, together with other conditions.", "Since 2026, new language and civic-examination requirements apply to certain first resident cards. The specific rules and exemptions must be checked before filing."] },
      { eyebrow: "Application file", title: "Prepare relevant evidence and a clear chronology", paragraphs: ["A strong application matches the correct legal basis with up-to-date documents. The authorities should be able to understand the immigration history, professional project or ties relied on."], points: ["Current permit, visa and evidence of lawful residence", "Contract, degrees, employer certificates or project documents", "Civil-status documents, address, resources, health cover and family evidence", "Filing certificates, requests for further documents and correspondence"] },
      { eyebrow: "Renewals and appeals", title: "Plan ahead for expiry and review every decision received", paragraphs: ["A change of employer, assignment, project or family circumstances may affect the appropriate legal basis at renewal. The official timetable should be checked and evidence retained.", "In a refusal, withdrawal, filing difficulty or prolonged silence, the strategy depends on the decision, notification and immigration status. No universal deadline applies without reading the documents."] },
    ],
    proofTitle: "An approach tailored to complex residence permits",
    proofItems: [
      { title: "Choice of legal basis", text: "Compare the permits and choose the one matching the actual circumstances." },
      { title: "Review of supporting documents", text: "Check the professional, economic, family and immigration evidence." },
      { title: "Planning ahead", text: "Identify deadlines and changes that could weaken an application or renewal." },
      { title: "Administrative decision", text: "Analyse the reasons, notification and available remedy." },
    ],
    faqTitle: "Talent residence permits and resident cards: frequently asked questions",
    faqItems: [
      { question: "Talent residence permit or Talent Passport: which term should I use?", answer: "‘Talent residence permit’ is the current term used by Service-Public and the relevant French code. ‘Talent Passport’ is still used in some visas, forms and contexts." },
      { question: "What is the difference between a talent residence permit and a resident card?", answer: "The talent permit is linked to professional, scientific, artistic or economic categories. Resident cards are available on several different legal grounds. They are not interchangeable." },
      { question: "Do all talent residence permit applications have the same requirements?", answer: "No. The evidence and criteria vary according to the ground relied on and whether the person applies from France or abroad." },
      { question: "Must I have lived in France for five years to obtain any resident card?", answer: "No. The EU long-term resident card generally requires five years, but other resident cards may be issued on different grounds." },
      { question: "Why have the application checked before filing?", answer: "A review identifies the appropriate permit, checks the requirements and spots inconsistencies before they cause difficulties." },
      { question: "What should I do after a refusal or renewal problem?", answer: "Keep the complete decision, date and proof of notification, filing certificates and correspondence. The remedy and deadline must be checked promptly." },
    ],
    updatedAt: "1 September 2026",
    sourceItems: [
      { label: "Service-Public — Multi-year ‘talent’ residence permit", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F16922" },
      { label: "Ministry of the Interior — Talent residence permit categories", href: "https://www.immigration.interieur.gouv.fr/limmigration-en-france/sejour-des-etrangers/limmigration-professionnelle-et-etudiante" },
      { label: "Service-Public — Ten-year resident card", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F2208" },
      { label: "Service-Public — EU long-term resident card", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F17359" },
      { label: "Service-Public — Permanent resident card", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F11201" },
    ],
    relatedTitle: "Useful immigration and nationality law pages",
    relatedItems: [
      { href: "/en/immigration-law", label: "Immigration law", text: "Residence applications and appeals." },
      { href: "/en/immigration-lawyer-paris", label: "Immigration lawyer in Paris", text: "Legal assistance with immigration procedures and disputes." },
      { href: "/en/french-nationality-law", label: "French nationality law", text: "Naturalisation, assessment and decisions." },
      { href: "/en/oqtf-lawyer-paris", label: "OQTF lawyer in Paris", text: "Respond quickly to an order to leave French territory." },
    ],
    ctaTitle: "Have the permit, supporting documents and timetable reviewed",
    ctaText: "State your nationality, place of residence, current permit, expiry date and objective. If you received a decision, attach it in full with proof of notification.",
  },

  "naturalisation-lawyer-paris": {
    metadata: { title: "Naturalisation lawyer in Paris", description: "Sophie Maréchal assists with French naturalisation applications in Paris, from eligibility and supporting documents to refusals, deferrals and appeals.", path: "/en/naturalisation-lawyer-paris", keywords: ["naturalisation lawyer Paris", "naturalization lawyer Paris", "French citizenship lawyer Paris"] },
    serviceType: "French naturalisation applications and appeals",
    breadcrumbs: [{ label: "Home", href: "/en" }, { label: "Practice areas", href: "/en/practice-areas" }, { label: "French nationality law", href: "/en/french-nationality-law" }, { label: "Naturalisation in Paris" }],
    eyebrow: "French nationality law · Paris", title: "Naturalisation lawyer in Paris", intro: "The firm assists with assessing, preparing and monitoring naturalisation applications, as well as reviewing adverse decisions.",
    notice: "The lawyer’s role is to make the application as legally robust and clearly presented as possible and to assess the available remedies. She cannot guarantee either the outcome or the authorities’ processing time.",
    sections: [
      { eyebrow: "Before filing", title: "Check the procedure and potential weaknesses in the application", paragraphs: ["An initial consultation can establish whether naturalisation by decree is appropriate and whether this is the right time to apply. Length of residence is only one factor.", "The firm considers continuity of residence, centre of interests in France, family circumstances, professional integration, resources, proficiency in French and administrative or criminal issues."] },
      { eyebrow: "Supporting documents", title: "Present a clear chronology and consistent evidence", paragraphs: ["The strength of an application depends less on volume than on relevance and consistency. Civil-status records, translations, proof of address, tax notices, contracts, payslips and family documents must match the circumstances declared.", "The review identifies poorly documented periods, discrepancies and changes that should be explained."], points: ["Identify documents relevant to personal circumstances", "Check translations and formal requirements for foreign civil-status records", "Explain changes in family, employment or address", "Keep filing confirmations and correspondence"] },
      { eyebrow: "Processing", title: "Plan for the 2026 rules and respond to requests for further documents", paragraphs: ["Since 1 January 2026, an application generally requires B2-level French, spoken and written, and a pass in the civic examination. The interview at the prefecture remains separate.", "Any significant change must be reported. Requests for documents should be answered within the stated deadline without contradicting information already provided."] },
      { eyebrow: "Paris", title: "Administrative jurisdiction is determined by the applicant’s home address", paragraphs: ["For someone living in Paris, the listed naturalisation platform is part of the Paris Police Prefecture. Elsewhere in Île-de-France, the platform for the relevant department applies.", "The firm can assist while taking account of the responsible office and filing procedure, but cannot act in the applicant’s place for personal steps."] },
      { eyebrow: "Appeals", title: "Review the decision and its notification carefully", paragraphs: ["Inadmissibility, refusal, deferral and closure without further action have different causes and consequences. The complete decision is needed to identify the response.", "Where a prior administrative appeal is mandatory, it must precede court proceedings. Consulting a lawyer does not suspend the deadline."] },
    ],
    proofTitle: "Legal assistance at every key stage",
    proofItems: [
      { title: "Initial assessment", text: "Check the correct procedure, authority and whether filing is appropriate." },
      { title: "Document review", text: "Check consistency and prepare explanations before submission." },
      { title: "Support during processing", text: "Review requests for further documents and changes to report." },
      { title: "Decision and appeal", text: "Identify the decision, preserve deadlines and prepare the appropriate appeal." },
    ],
    faqTitle: "Naturalisation in Paris: frequently asked questions",
    faqItems: [
      { question: "When should I consult a lawyer about naturalisation?", answer: "Before filing if an aspect is weak, during processing after a request for documents, or immediately after an inadmissibility, refusal, deferral or closure." },
      { question: "Which documents should I bring to the first consultation?", answer: "Identity and residence documents, civil-status records, proof of address, family, employment, income and tax, plus receipts, emails and decisions." },
      { question: "Can the lawyer guarantee that naturalisation will be granted?", answer: "No. Legal assistance identifies the procedure and difficulties and helps present a consistent application, but cannot guarantee the decision or processing time." },
      { question: "Which office handles an application filed by someone living in Paris?", answer: "Jurisdiction depends on the home address. For Paris, the official directory identifies the Paris Police Prefecture’s naturalisation platform." },
      { question: "What should I provide after an adverse decision?", answer: "Send the complete decision, date and proof of notification, filing receipt, submitted documents and correspondence promptly." },
    ],
    updatedAt: "1 September 2026",
    sourceItems: [
      { label: "Service-Public — French naturalisation by decree", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F2213" },
      { label: "Service-Public — French-language level required for French nationality", href: "https://www.service-public.gouv.fr/particuliers/vosdroits/F11926" },
      { label: "Ministry of the Interior — Civic examination for naturalisation", href: "https://www.immigration.interieur.gouv.fr/documentation/guides-textes-et-brochures/lexamen-civique-pour-demande-de-naturalisation-ou-de-reintegration-dans-nationalite-francaise.html" },
      { label: "Ministry of the Interior — Disputes concerning access to French nationality", href: "https://www.immigration.interieur.gouv.fr/devenir-francais/contentieux-de-lacces-a-nationalite-francaise" },
      { label: "Service-Public directory — Paris naturalisation platform", href: "https://lannuaire.service-public.gouv.fr/ile-de-france/paris/fe03148c-ac19-4ee3-ae43-51f391bf980c" },
    ],
    relatedTitle: "Understand the legal framework and related procedures",
    relatedItems: [
      { href: "/en/french-nationality-law", label: "French nationality law", text: "Naturalisation framework, assessment and decisions." },
      { href: "/en/immigration-law", label: "Immigration law", text: "Residence procedures and appeals." },
      { href: "/en/talent-passport-resident-card-lawyer-paris", label: "Talent residence permit and resident card", text: "Prepare a permit application suited to the circumstances." },
      { href: "/en/contact", label: "Tell us about your situation", text: "Provide facts, dates and documents before a consultation." },
    ],
    ctaTitle: "Prepare an application or preserve an appeal deadline",
    ctaText: "For an adverse decision, send it in full with its date and proof of notification. For a planned application, state your home address, immigration status and main stages of residence in France.",
  },
};
